<?php

########################################################################
# Extension Manager/Repository config file for ext: "pchart"
#
# Auto generated by Extbase Kickstarter 2011-03-15
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'PHPlot Integration',
	'description' => 'Integration of the PHPlot library for drawing all kinds of charts (http://http://phplot.sourceforge.net/).',
	'category' => 'misc',
	'author' => 'Francois Suter',
	'author_email' => 'typo3@cobweb.ch',
	'author_company' => 'Cobweb',
	'shy' => '',
	'dependencies' => '',
	'conflicts' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>